package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class Boveda_Botanica extends javax.swing.JFrame {

    /**
     * Creates new form Boveda_Botanica
     */
    public Boveda_Botanica() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        tabla_boveda.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("Especie");
        modelo.addColumn("Núm. Serie");
        modelo.addColumn("Estatus");
        modelo.addColumn("Fecha Siembra");
        
        try {
            java.sql.Connection cn = clases.Conexion.conectar();
            
            java.sql.PreparedStatement pst = cn.prepareStatement (
                "select id_planta, especie, num_serie, estatus, fecha_siembra from plantas where estatus = 'Archivada'"
            );
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {                
                Object [] fila = new Object [5];
                fila[0] = rs.getInt("id_planta");
                fila[1] = rs.getString("especie"); 
                fila[2] = rs.getString("num_serie"); 
                fila[3] = rs.getString("estatus"); 
                fila[4] = rs.getString("fecha_siembra"); 
                
                modelo.addRow(fila);
            }
            cn.close();
            
        } catch (Exception e) {
            System.err.println("Error al llenar tabla de Bóveda: " + e);
            javax.swing.JOptionPane.showMessageDialog(null, "Error al cargar el Archivo Histórico.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_boveda = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivo Histórico Botánico");

        tabla_boveda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_boveda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_bovedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_boveda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_bovedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_bovedaMouseClicked
        // TODO add your handling code here:
        int fila_clic = tabla_boveda.rowAtPoint(evt.getPoint());
        
        if (fila_clic > -1) {
            ventanas.Inventario_Plantas.id_planta_update = Integer.parseInt(tabla_boveda.getValueAt(fila_clic, 0).toString());
            
            Informacion_Planta ventanaInfo = new Informacion_Planta();
            ventanaInfo.setVisible(true);
        }
    }//GEN-LAST:event_tabla_bovedaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boveda_Botanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boveda_Botanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boveda_Botanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boveda_Botanica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boveda_Botanica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_boveda;
    // End of variables declaration//GEN-END:variables
}
