package ventanas;

/**
 *
 * @author Samuel Males Williams.
 */
public class Calculadora_Crecimiento extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora_Crecimiento
     */
    public Calculadora_Crecimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_fecha1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_altura1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_fecha2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_altura2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        lbl_resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Módulo de Análisis: Tasa de Crecimiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, -1));

        jLabel2.setText("Fecha 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 20));
        getContentPane().add(txt_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 140, -1));

        jLabel3.setText("(DD/MM/AAAA)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, -1));

        jLabel4.setText("Altura 1:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 20));

        txt_altura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_altura1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt_altura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, -1));

        jLabel5.setText("(cm)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 90, -1));

        jLabel6.setText("Fecha 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 80, 20));
        getContentPane().add(txt_fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 140, -1));

        jLabel7.setText("Altura 2:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, -1));
        getContentPane().add(txt_altura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 180, -1));

        jLabel8.setText("(DD/MM/AAAA)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, -1));

        jLabel9.setText("(cm)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        btn_calcular.setText("Calcular Tasa (m)");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 150, -1));

        lbl_resultado.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        lbl_resultado.setText("Tasa de Crecimiento Diario: 0.00 cm/día");
        getContentPane().add(lbl_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 360, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_altura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_altura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_altura1ActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        // TODO add your handling code here:
        String strFecha1 = txt_fecha1.getText().trim();
        String strAltura1 = txt_altura1.getText().trim();
        String strFecha2 = txt_fecha2.getText().trim();
        String strAltura2 = txt_altura2.getText().trim();
        
        if (strFecha1.isEmpty() || strAltura1.isEmpty()  || strFecha2.isEmpty() || strAltura2.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        } else {
            try {
                
                double y1 = Double.parseDouble(strAltura1);
                double y2 = Double.parseDouble(strAltura2);
                
                java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                java.time.LocalDate fecha1 = java.time.LocalDate.parse(strFecha1, formato);
                java.time.LocalDate fecha2 = java.time.LocalDate.parse(strFecha2, formato);
                
                long deltaX = java.time.temporal.ChronoUnit.DAYS.between(fecha1, fecha2);
                
                if (deltaX == 0) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Matemáticamente inválido: Las fechas son iguales (División por cero).");
                } else if (deltaX < 0) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Lógica temporal invertida: La fecha #2 debe ser posterior a la fecha #1.");
                } else {
                    double deltaY = y2 - y1;
                    double tasaCrecimiento = deltaY / deltaX;
                    
                    String resultadoFormateado = String.format("%.2f", tasaCrecimiento);
                    lbl_resultado.setText("Tasa de Crecimiento Diario: " + resultadoFormateado);
                    
                    if (tasaCrecimiento > 0) {
                        lbl_resultado.setForeground(new java.awt.Color(0, 153, 0));
                    } else if (tasaCrecimiento < 0) {
                        lbl_resultado.setForeground(java.awt.Color.RED);
                    } else {
                        lbl_resultado.setForeground(java.awt.Color.BLACK);
                    }
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error de formato: La alturas deben ser números");
            } catch (java.time.format.DateTimeParseException e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error temporal: El formato de fecha debe ser el indicado.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(null, "Error en el cálculo: " + e);
            }
        }
    }//GEN-LAST:event_btn_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Crecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Crecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Crecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora_Crecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora_Crecimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_altura1;
    private javax.swing.JTextField txt_altura2;
    private javax.swing.JTextField txt_fecha1;
    private javax.swing.JTextField txt_fecha2;
    // End of variables declaration//GEN-END:variables
}
