package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class GestionarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form GestionarUsuarios
     */
    public GestionarUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        table_usuarios.setModel(modelo);
        modelo.addColumn("ID");
        modelo.addColumn("Nombre Real");
        modelo.addColumn("Usuario (Login)");
        modelo.addColumn("Rol");
        modelo.addColumn("Estatus");
        
        try {
            java.sql.Connection cn = clases.Conexion.conectar();
            java.sql.PreparedStatement pst = cn.prepareStatement(
                "select id_usuario, nombre_Real, nombre_usuario, nivel_permiso, estatus from usuarios"
            );
            
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {                
                
                Object[] fila = new Object[5];
                
                fila[0] = rs.getInt("id_usuario");
                fila[1] = rs.getString("nombre_real");
                fila[2] = rs.getString("nombre_usuario");
                fila[3] = rs.getString("nivel_permiso");
                fila[4] = rs.getString("estatus");
                
                modelo.addRow(fila);
            }
            
            cn.close();
        } catch (java.sql.SQLException e) {
            System.err.println("Error al llenar la tabla de usuarios: " + e);
            javax.swing.JOptionPane.showMessageDialog(null, "Error al cargar los datos. Contacte al desarrollador.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_usuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gestión de Personal Registrado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        table_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_usuarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 560, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_usuarios;
    // End of variables declaration//GEN-END:variables
}
