package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class Gestion_Plantas extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Plantas
     */
    public Gestion_Plantas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbm_tipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_especie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbm_estatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        btn_registrarPln = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro de Nueva Planta.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, -1));

        jLabel2.setText("Tipo de Planta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, 20));

        cbm_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frutal", "Ornamental", "Medicinal", "Hortaliza" }));
        getContentPane().add(cbm_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 120, -1));

        jLabel3.setText("Nombre común");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 40));
        getContentPane().add(txt_especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jLabel4.setText("<html>Fecha de<br>siembra</html>");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 40));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 170, -1));

        jLabel5.setText("Estatus actual");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 40));

        cbm_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semilla", "Brote", "Crecimiento", "En Tratamiento", "Sana", "Archivada" }));
        getContentPane().add(cbm_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, -1));

        jLabel6.setText("DD/MM/AAAA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        jLabel7.setText("Observaciones iniciales:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 150, -1));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 320, 180));

        btn_registrarPln.setText("Registrar Planta");
        btn_registrarPln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarPlnActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarPln, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarPlnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarPlnActionPerformed
        // TODO add your handling code here:
        String tipo = cbm_tipo.getSelectedItem().toString();
        String especie = txt_especie.getText().trim();
        String fecha = txt_fecha.getText().trim();
        String estatus = cbm_estatus.getSelectedItem().toString();
        String observaciones = txt_observaciones.getText().trim();
        String usuario_actual = ventanas.Login.user;
        
        if (especie.equals("") || fecha.equals("") || observaciones.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "¡Atencion! Faltan datos críticos (Especie, Fecha u Observaciones).");
        } else {
            try {
                java.sql.Connection cn = clases.Conexion.conectar();
                
                java.sql.PreparedStatement pst = cn.prepareStatement(
                        "insert into plantas values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
                );
                
                java.util.Calendar cal = java.util.Calendar.getInstance();
                String dia = Integer.toString(cal.get(java.util.Calendar.DATE));
                String mes = Integer.toString(cal.get(java.util.Calendar.MONTH));
                String annio = Integer.toString(cal.get(java.util.Calendar.YEAR));
                
                String numSerie = "BIO-" + annio + "-" + (int)(Math.random() * 10000);
                
                pst.setInt(1,0);
                pst.setInt(2,1);
                pst.setString(3, tipo);
                pst.setString(4, especie);
                pst.setString(5, fecha);
                pst.setString(6, numSerie);
                pst.setString(7, dia);
                pst.setString(8, mes);
                pst.setString(9, annio);
                pst.setString(10, observaciones);
                pst.setString(11, estatus);
                pst.setString(12, usuario_actual);
                pst.setString(13, "");
                pst.setString(14, "");
                
                pst.executeUpdate();
                cn.close();
                
                txt_especie.setText("");
                txt_fecha.setText("");
                txt_observaciones.setText("");
                cbm_tipo.setSelectedIndex(0);
                cbm_estatus.setSelectedIndex(0);
                
                javax.swing.JOptionPane.showMessageDialog(null,"¡Planta registrada con éxito!\nNúmero de serie asignado: " + numSerie);
                
            } catch (java.sql.SQLException e) {
                System.err.println("Error al registrar planta: " + e);
                javax.swing.JOptionPane.showMessageDialog(null,"Error al guardar en Base de Datos. Contacte al desarrollador.");
            }
        }
    }//GEN-LAST:event_btn_registrarPlnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrarPln;
    private javax.swing.JComboBox<String> cbm_estatus;
    private javax.swing.JComboBox<String> cbm_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_especie;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextArea txt_observaciones;
    // End of variables declaration//GEN-END:variables
}
