package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class Informacion_Planta extends javax.swing.JFrame {

    /**
     * Creates new form Informacion_Planta
     */
    public Informacion_Planta() {
        initComponents();

        this.setLocationRelativeTo(null);

        txt_idPlanta.setEditable(false);
        txt_numSerie.setEditable(false);
        txt_fechaSiembra.setEditable(false);

        int id_planta = ventanas.Inventario_Plantas.id_planta_update;

        try {
            java.sql.Connection cn = clases.Conexion.conectar();

            java.sql.PreparedStatement pst = cn.prepareStatement(
                    "select id_planta, num_serie, fecha_siembra, especie, estatus, observaciones from plantas where id_planta = '" + id_planta + "'"
            );
            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_idPlanta.setText(rs.getString("id_planta"));
                txt_numSerie.setText(rs.getString("num_serie"));
                txt_fechaSiembra.setText(rs.getString("fecha_siembra"));
                txt_especie.setText(rs.getString("especie"));

                cmb_estatus.setSelectedItem(rs.getString("estatus"));

                txt_comentarios.setText(rs.getString("observaciones"));
            }
            cn.close();

        } catch (Exception e) {
            System.err.println("Error en cargar información de la planta: " + e);
            javax.swing.JOptionPane.showMessageDialog(null, "Error al cargar el expediente. Contacte al desarrollador.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_idPlanta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_numSerie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_fechaSiembra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_especie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_estatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_comentarios = new javax.swing.JTextArea();
        btn_actualizarExp = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Expediente Botánico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 70, 20));
        getContentPane().add(txt_idPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 20));

        jLabel3.setText("Núm. Serie:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 70, 20));

        txt_numSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numSerieActionPerformed(evt);
            }
        });
        getContentPane().add(txt_numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 190, 20));

        jLabel4.setText("<html>Fecha de<br>siembra:</html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 162, 70, 40));
        getContentPane().add(txt_fechaSiembra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, -1));

        jLabel5.setText("Especie:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 70, 40));
        getContentPane().add(txt_especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, -1));

        jLabel6.setText("Estatus:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 70, 40));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semilla", "Brote", "Crecimiento", "En Tratamiento", "Sana", "Archivada" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 130, -1));

        jLabel7.setText("<html>C. Técnicos<br>Novedades:</html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 70, -1));

        txt_comentarios.setColumns(20);
        txt_comentarios.setRows(5);
        jScrollPane1.setViewportView(txt_comentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 350, 150));

        btn_actualizarExp.setText("Actualizar Expediente");
        btn_actualizarExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarExpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizarExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 150, -1));

        btn_pdf.setText("Generar Reporte (PDF)");
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 150, -1));

        jButton1.setText("Calcular Crecimiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_numSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numSerieActionPerformed

    private void btn_actualizarExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarExpActionPerformed
        // TODO add your handling code here:
        String especie = txt_especie.getText().trim();
        String estatus = cmb_estatus.getSelectedItem().toString();
        String comentarios = txt_comentarios.getText();
        String usuario_actual = ventanas.Login.user;

        String id_planta = txt_idPlanta.getText();

        if (especie.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "El campo de especie no puede estar vacío.");
        } else {
            try {
                java.sql.Connection cn = clases.Conexion.conectar();

                java.sql.PreparedStatement pst = cn.prepareStatement(
                        "update plantas set especie=?, estatus=?, observaciones=?, ultima_modificacion=? where id_planta = '" + id_planta + "'"
                );

                pst.setString(1, especie);
                pst.setString(2, estatus);
                pst.setString(3, comentarios);
                pst.setString(4, usuario_actual);

                pst.executeUpdate();
                cn.close();

                javax.swing.JOptionPane.showMessageDialog(null, "¡Expediente botánico actualizado exitosamente!");

                this.dispose();

            } catch (Exception e) {
                System.err.println("Error al actualizar planta: " + e);
                javax.swing.JOptionPane.showMessageDialog(null, "Error al actualizar expediente. Contacte con el desarrollador.");
            }
        }
    }//GEN-LAST:event_btn_actualizarExpActionPerformed

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed
        // TODO add your handling code here:
        // 1. Creamos la ventana de "Guardar como..."
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setDialogTitle("Guardar Expediente PDF");
        // Le damos un nombre por defecto al archivo usando tu número de serie
        selector.setSelectedFile(new java.io.File("Expediente_" + txt_numSerie.getText() + ".pdf"));

        // 2. Mostramos la ventana y capturamos qué botón apretó el usuario
        int opcion = selector.showSaveDialog(this);

        // 3. Si el usuario le dio clic al botón "Guardar"
        if (opcion == javax.swing.JFileChooser.APPROVE_OPTION) {

            // Obtenemos la ruta exacta que el usuario eligió
            String ruta = selector.getSelectedFile().getAbsolutePath();

            // --- AQUÍ EMPIEZA LA CREACIÓN DEL PDF ---
            com.itextpdf.text.Document documento = new com.itextpdf.text.Document();

            try {
                com.itextpdf.text.pdf.PdfWriter.getInstance(documento, new java.io.FileOutputStream(ruta));
                documento.open();

                // Diseñamos las fuentes
                com.itextpdf.text.Font fuenteTitulo = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_BOLD, 18, com.itextpdf.text.BaseColor.DARK_GRAY);
                com.itextpdf.text.Font fuenteNormal = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA, 12, com.itextpdf.text.BaseColor.BLACK);
                com.itextpdf.text.Font fuenteNegrita = com.itextpdf.text.FontFactory.getFont(com.itextpdf.text.FontFactory.HELVETICA_BOLD, 12, com.itextpdf.text.BaseColor.BLACK);

                // Agregamos el Título
                com.itextpdf.text.Paragraph titulo = new com.itextpdf.text.Paragraph("Expediente Clínico Botánico\nBio-Logic Manager\n\n", fuenteTitulo);
                titulo.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                documento.add(titulo);

                // Inyectamos la Identidad
                documento.add(new com.itextpdf.text.Paragraph("Identidad del Paciente Verde:\n\n", fuenteNegrita));
                documento.add(new com.itextpdf.text.Paragraph("Número de Serie: " + txt_numSerie.getText(), fuenteNormal));
                documento.add(new com.itextpdf.text.Paragraph("Especie: " + txt_especie.getText(), fuenteNormal));
                documento.add(new com.itextpdf.text.Paragraph("Fecha de Siembra: " + txt_fechaSiembra.getText(), fuenteNormal));
                documento.add(new com.itextpdf.text.Paragraph("Estatus Actual: " + cmb_estatus.getSelectedItem().toString(), fuenteNormal));

                // Inyectamos las Observaciones
                documento.add(new com.itextpdf.text.Paragraph("\nHistorial Clínico y Observaciones:\n", fuenteNegrita));
                documento.add(new com.itextpdf.text.Paragraph(txt_comentarios.getText(), fuenteNormal));

                // Firmamos
                documento.add(new com.itextpdf.text.Paragraph("\n\nDocumento generado por: " + ventanas.Login.user, fuenteNormal));

                documento.close();

                javax.swing.JOptionPane.showMessageDialog(null, "¡Reporte PDF guardado exitosamente!");

            } catch (Exception e) {
                System.err.println("Error al generar PDF: " + e);
                javax.swing.JOptionPane.showMessageDialog(null, "Error al generar el documento PDF. Contacte al desarrollador.");
            }
        }
    }//GEN-LAST:event_btn_pdfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Calculadora_Crecimiento calc = new Calculadora_Crecimiento();
        calc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_Planta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_Planta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_Planta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_Planta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_Planta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizarExp;
    private javax.swing.JButton btn_pdf;
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_comentarios;
    private javax.swing.JTextField txt_especie;
    private javax.swing.JTextField txt_fechaSiembra;
    private javax.swing.JTextField txt_idPlanta;
    private javax.swing.JTextField txt_numSerie;
    // End of variables declaration//GEN-END:variables
}
