package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class Interfaz_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Principal
     */
    public Interfaz_Principal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        String nombreUsuario = ventanas.Login.user;
        
        lbl_bienvenida.setText("Bienvenid@ " + nombreUsuario + " - Centro de Mando");
        
        try {
            
            java.sql.Connection cn = clases.Conexion.conectar();
            
            java.sql.PreparedStatement pst = cn.prepareStatement(
                    "select nivel_permiso from usuarios where nombre_usuario = '" + ventanas.Login.user + "'"
            );
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                String permiso = rs.getString("nivel_permiso");
                
                if (!permiso.equals("Administrador")) {
                    btn_registrarUsuario.setVisible(false);
                    btn_gestionarUsuarios.setVisible(false);
                }
            }
            cn.close();
            
        } catch (Exception e) {
            System.err.println("Error en el filtro de seguridad: " + e);
        }
        
        this.setLocationRelativeTo(null);
        
        try {
            
            java.sql.Connection cn = clases.Conexion.conectar();
            
            java.sql.PreparedStatement pst1 = cn.prepareStatement(
                    "select count(*) from plantas where estatus != 'Archivada'"
            );
            
            java.sql.ResultSet rs1 = pst1.executeQuery();
            
            if (rs1.next()) {
                lbl_totalPrincipal.setText(rs1.getString(1));
            }
            
            java.sql.PreparedStatement pst2 = cn.prepareStatement(
                    "select count(*) from plantas where estatus = 'En Tratamiento'"
            );
            
            java.sql.ResultSet rs2 = pst2.executeQuery();
            
            if (rs2.next()) {
                lbl_tratamiento.setText(rs2.getString(1));
            }
            
            java.sql.PreparedStatement pst3 = cn.prepareStatement(
                    "select count(*) from plantas where estatus = 'Archivada'"
            );
            
            java.sql.ResultSet rs3 = pst3.executeQuery();
            
            if (rs3.next()) {
                lbl_archivo.setText(rs3.getString(1));
            }
            
            cn.close();
 
        } catch (Exception e) {
            System.err.println("Error al cargar el Dashboard: " + e);
            javax.swing.JOptionPane.showMessageDialog(null, "Error al cargar las estadísticas del sistema.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenida = new javax.swing.JLabel();
        btn_registrarUsuario = new javax.swing.JButton();
        btn_gestionarUsuarios = new javax.swing.JButton();
        btn_gestionPlantas = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_totalPrincipal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_tratamiento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_archivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bienvenida.setText("Bienvenido");
        getContentPane().add(lbl_bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, -1));

        btn_registrarUsuario.setText("Registrar Usuario");
        btn_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, -1));

        btn_gestionarUsuarios.setText("Gestionar Usuarios");
        btn_gestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 170, -1));

        btn_gestionPlantas.setText("Gestión Botánica (Plantas)");
        btn_gestionPlantas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionPlantasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_gestionPlantas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 170, -1));

        btn_inventario.setText("Ver Inventario");
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 170, -1));

        jButton1.setText("Archivo Histórico");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 170, -1));

        jLabel1.setText("TOTAL DE PLANTAS ACTIVAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 160, -1));

        lbl_totalPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_totalPrincipal.setText("0");
        getContentPane().add(lbl_totalPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 70, 20));

        jLabel2.setText("PACIENTES EN TRATAMIENTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 170, -1));

        lbl_tratamiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tratamiento.setText("0");
        getContentPane().add(lbl_tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 80, -1));

        jLabel3.setText("PLANTAS ARCHIVADAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 130, -1));

        lbl_archivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_archivo.setText("0");
        getContentPane().add(lbl_archivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarUsuarioActionPerformed
        // TODO add your handling code here:
        Registro_Usuarios ventanaRegistro = new Registro_Usuarios();
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_btn_registrarUsuarioActionPerformed

    private void btn_gestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionarUsuariosActionPerformed
        // TODO add your handling code here:
        GestionarUsuarios ventanaGestion = new GestionarUsuarios();
        ventanaGestion.setVisible(true);
    }//GEN-LAST:event_btn_gestionarUsuariosActionPerformed

    private void btn_gestionPlantasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionPlantasActionPerformed
        // TODO add your handling code here:
        Gestion_Plantas ventanaPlantas = new Gestion_Plantas();
        ventanaPlantas.setVisible(true);
    }//GEN-LAST:event_btn_gestionPlantasActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        // TODO add your handling code here:
        Inventario_Plantas ventanaInventario = new Inventario_Plantas();
        ventanaInventario.setVisible(true);
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Boveda_Botanica ventanaBoveda = new Boveda_Botanica();
        ventanaBoveda.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gestionPlantas;
    private javax.swing.JButton btn_gestionarUsuarios;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_registrarUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_archivo;
    private javax.swing.JLabel lbl_bienvenida;
    private javax.swing.JLabel lbl_totalPrincipal;
    private javax.swing.JLabel lbl_tratamiento;
    // End of variables declaration//GEN-END:variables
}
