package ventanas;

/**
 *
 * @author Samuel Males Williams
 */
public class Inventario_Plantas extends javax.swing.JFrame {
    
    public static int id_planta_update = 0;

    /**
     * Creates new form Inventario_Plantas
     */
    public Inventario_Plantas() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        tabla_inventario.setModel(modelo);
        
        modelo.addColumn("ID");
        modelo.addColumn("Especie");
        modelo.addColumn("Núm. Serie");
        modelo.addColumn("Estatus");
        modelo.addColumn("Fecha Siembra");
        
        try {
            java.sql.Connection cn = clases.Conexion.conectar();
            
            java.sql.PreparedStatement pst = cn.prepareStatement(
                    "select id_planta, especie, num_serie, estatus, fecha_siembra from plantas where estatus != 'Archivada'"
            );
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                Object [] fila = new Object [5];
                fila[0] = rs.getInt("id_planta");
                fila[1] = rs.getString("especie");
                fila[2] = rs.getString("num_serie");
                fila[3] = rs.getString("estatus");
                fila[4] = rs.getString("fecha_siembra");
                modelo.addRow(fila);
            }
            cn.close();
            
        } catch (Exception e) {
            System.err.println("Error al llenar tabla de plantas: " + e);
            javax.swing.JOptionPane.showMessageDialog(null, "Error al cargar inventario. Contacte al desarrollador.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inventario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_buscador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Inventario Botánico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_inventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_inventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 520, 540));

        jLabel2.setText("Buscar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, 40));

        txt_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscadorKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabla_inventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_inventarioMouseClicked
        // TODO add your handling code here:
        int fila_clic = tabla_inventario.rowAtPoint(evt.getPoint());
        
        if (fila_clic > -1) {
            id_planta_update = Integer.parseInt(tabla_inventario.getValueAt(fila_clic, 0).toString());
            
            Informacion_Planta ventanaInfo = new Informacion_Planta();
            ventanaInfo.setVisible(true);
        }
    }//GEN-LAST:event_tabla_inventarioMouseClicked

    private void txt_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorKeyReleased
        // TODO add your handling code here:
        String textoBuscado =  txt_buscador.getText();
        
        javax.swing.table.TableRowSorter<javax.swing.table.TableModel> trs = new javax.swing.table.TableRowSorter<>(tabla_inventario.getModel());
        
        tabla_inventario.setRowSorter(trs);
        
        if (textoBuscado.trim().length() == 0) {
            trs.setRowFilter(null);
        } else {
            trs.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + textoBuscado));
        }
    }//GEN-LAST:event_txt_buscadorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventario_Plantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventario_Plantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_inventario;
    private javax.swing.JTextField txt_buscador;
    // End of variables declaration//GEN-END:variables
}
